# Generated by Django 4.1.3 on 2022-11-13 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plastics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Origen',
                'verbose_name_plural': 'Origenes',
            },
        ),
        migrations.CreateModel(
            name='User_Plastic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='plastic/', verbose_name='Imagen')),
                ('description', models.CharField(max_length=500, verbose_name='Descripción')),
                ('units', models.BigIntegerField(blank=True, null=True, verbose_name='Unidades')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_plastics.origin', verbose_name='Origen')),
                ('plastic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plastics.plastic', verbose_name='Plástico')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Plastico de usuario',
                'verbose_name_plural': 'Plasticos de usuario',
            },
        ),
    ]
