# Generated by Django 4.1.3 on 2022-11-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_plastics', '0002_alter_user_plastic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_plastic',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='plastic/', verbose_name='Imagen'),
        ),
    ]
